<a href="https://colab.research.google.com/github/yongug/2621/blob/master/1_lecture_skt_flyai_ipynb%EC%9D%98_%EC%82%AC%EB%B3%B8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
print("hi")

hi


In [ ]:
a = 1
b = 3
print(a+b)

4


In [ ]:
!pip install numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])

In [ ]:
print(arr)

[1 2 3 4]


In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [ ]:
print(type(arr2))

<class 'numpy.ndarray'>


In [ ]:
print(arr2)

[[1 2 3 4]
 [5 6 7 8]]


In [ ]:
print(arr2[1][1])

6


In [ ]:
print(arr2[1,1])

6


In [ ]:
arr2.shape

(2, 4)

In [ ]:
arr3 = np.arange(1,10,2)


In [ ]:
print(arr3)

[1 3 5 7 9]


In [ ]:
arr4 = np.linspace(0,4,5)
print(arr4)

[0. 1. 2. 3. 4.]


In [ ]:
arr5 = np.zeros((2,3))

In [ ]:
print(arr5)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr6 = np.ones((3,2,4))
print(arr6)

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]]]


In [ ]:
arr7 = np.zeros((2,3))
print(arr7)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
arr8 = np.full((2,3),5)
print(arr8)

[[5 5 5]
 [5 5 5]]


In [ ]:
my_list = np.array([1,2,3,4,5,6,7,8])

In [ ]:
print(my_list[3:])

[4 5 6 7 8]


In [ ]:
print(my_list[:5])

[1 2 3 4 5]


In [ ]:
print(my_list[2:6])

[3 4 5 6]


In [ ]:
print(my_list[:-2])

[1 2 3 4 5 6]


In [ ]:
print(my_list[:-4])

[1 2 3 4]


In [ ]:
print(my_list[-4:])

[5 6 7 8]


In [ ]:
print(my_list[1::2])

[2 4 6 8]


In [ ]:
print(my_list[1::])

[2 3 4 5 6 7 8]


In [ ]:
print(my_list[2:6:2])

[3 5]


In [ ]:
arr10 = np.array([[1, 2, 3, 4],
 [5, 6, 7, 8],
 [9, 10, 11, 12],
 [13, 14, 15, 16]])

In [ ]:
print(arr10)
print(arr10[:, 1:3])
print(arr10[:, :-1])
print(arr10[:, ::2])

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
[[ 1  2  3]
 [ 5  6  7]
 [ 9 10 11]
 [13 14 15]]
[[ 1  3]
 [ 5  7]
 [ 9 11]
 [13 15]]


In [7]:
!pip install pandas

In [8]:
import pandas as pd

In [9]:
titanic = pd.read_csv('./titanic.csv') # Change the path to the correct location
print('shape : ', titanic.shape )
print('dtypes :', titanic.dtypes)

shape :  (891, 12)
dtypes : PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object


In [ ]:
import numpy as np
import pandas as pd
z = [['Jackson', 68, True, np.NaN, 'A'],
['Liam', 74, True, 1.1, 'A'],
['Emma', np.NaN, False, 0.89, 'C'],
['James', 78, np.NaN, 0.91, 'C'],
['Ava', 54, False, 0.73, 'C'],
['Henry', 69, True, np.NaN, 'C']]
df = pd.DataFrame(data= z, columns=['Name', 'Weight', 'Option', 'Rate', 'Type'])
df

Name  Weight Option  Rate Type
0  Jackson    68.0   True   NaN    A
1     Liam    74.0   True  1.10    A
2     Emma     NaN  False  0.89    C
3    James    78.0    NaN  0.91    C
4      Ava    54.0  False  0.73    C
5    Henry    69.0   True   NaN    C

In [ ]:
df = pd.DataFrame({
'Weight':['68', '74','52','78','54','69'],
'Option':[True, True, False, True, False, True],
'Rate':[0.82, 1.1, 0.89, 0.91, 0.73, 0.78],
'Type':['A','B','C','C','B','C']
})
df
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Weight  6 non-null      object 
 1   Option  6 non-null      bool   
 2   Rate    6 non-null      float64
 3   Type    6 non-null      object 
dtypes: bool(1), float64(1), object(2)
memory usage: 278.0+ bytes


In [ ]:
df['Weight'] = pd.to_numeric(df['Weight'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Weight  6 non-null      int64  
 1   Option  6 non-null      bool   
 2   Rate    6 non-null      float64
 3   Type    6 non-null      object 
dtypes: bool(1), float64(1), int64(1), object(1)
memory usage: 278.0+ bytes


In [ ]:
df['Weight'] = df['Weight'].astype(str)
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   Weight  6 non-null      object 
 1   Option  6 non-null      bool   
 2   Rate    6 non-null      float64
 3   Type    6 non-null      object 
dtypes: bool(1), float64(1), object(2)
memory usage: 278.0+ bytes


In [ ]:
df

Weight  Option  Rate Type
0     68    True  0.82    A
1     74    True  1.10    B
2     52   False  0.89    C
3     78    True  0.91    C
4     54   False  0.73    B
5     69    True  0.78    C

In [ ]:
df['Weight'].mean()
#df['Weight'].var()

114575464244.83333

In [ ]:
df['Weight'].sum()

'687452785469'

In [ ]:
df['Weight'].count()

6

In [ ]:
df['Rate'].mean()


0.8716666666666667

In [ ]:
df['Rate'].var()


0.01701666666666668

In [ ]:
titanic

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

기항지 or 성별에 따른 티켓 등급 / 가격 알아보기

In [5]:
titanic = pd.read_csv('./titanic.csv')
titanic.head()


NameError: name 'pd' is not defined

In [ ]:
titanic.count()

PassengerId    891
Survived       891
Pclass         891
Name           891
Sex            891
Age            714
SibSp          891
Parch          891
Ticket         891
Fare           891
Cabin          204
Embarked       889
dtype: int64

In [ ]:
titanic[(titanic['Sex'] == 'female') & (titanic['Survived']==True)].count()

PassengerId    233
Survived       233
Pclass         233
Name           233
Sex            233
Age            197
SibSp          233
Parch          233
Ticket         233
Fare           233
Cabin           91
Embarked       231
dtype: int64

In [ ]:
titanic[(titanic['Sex'] == 'male') & (titanic['Survived']==True)].count()

PassengerId    109
Survived       109
Pclass         109
Name           109
Sex            109
Age             93
SibSp          109
Parch          109
Ticket         109
Fare           109
Cabin           45
Embarked       109
dtype: int64

In [1]:
titanic

NameError: name 'titanic' is not defined

In [10]:
titanic_sorted = titanic['Cabin'].sort_values()
titanic_sorted

583    A10
475    A14
556    A16
284    A19
599    A20
      ... 
884    NaN
885    NaN
886    NaN
888    NaN
890    NaN
Name: Cabin, Length: 891, dtype: object

In [13]:
(titanic_sorted['Cabin'][0] == 'C').sum()

KeyError: 'Cabin'

In [17]:
titanic[titanic['Cabin'].str.contains('A',na=False)].count()

PassengerId    15
Survived       15
Pclass         15
Name           15
Sex            15
Age            12
SibSp          15
Parch          15
Ticket         15
Fare           15
Cabin          15
Embarked       15
dtype: int64

In [18]:
titanic[titanic['Cabin'].str.contains('B',na=False)].count()

PassengerId    47
Survived       47
Pclass         47
Name           47
Sex            47
Age            45
SibSp          47
Parch          47
Ticket         47
Fare           47
Cabin          47
Embarked       45
dtype: int64

In [19]:
titanic[titanic['Cabin'].str.contains('C',na=False)].count()

PassengerId    59
Survived       59
Pclass         59
Name           59
Sex            59
Age            51
SibSp          59
Parch          59
Ticket         59
Fare           59
Cabin          59
Embarked       59
dtype: int64

In [22]:
titanic[titanic['Cabin'].str.contains('D',na=False) & titanic['Survived']==False].count()

PassengerId    866
Survived       866
Pclass         866
Name           866
Sex            866
Age            691
SibSp          866
Parch          866
Ticket         866
Fare           866
Cabin          179
Embarked       864
dtype: int64

In [23]:
titanic_sorted


583    A10
475    A14
556    A16
284    A19
599    A20
      ... 
884    NaN
885    NaN
886    NaN
888    NaN
890    NaN
Name: Cabin, Length: 891, dtype: object

In [28]:
titanic[titanic['Survived']==True].count()

PassengerId    342
Survived       342
Pclass         342
Name           342
Sex            342
Age            290
SibSp          342
Parch          342
Ticket         342
Fare           342
Cabin          136
Embarked       340
dtype: int64